ethnic_groups = {
    "Abah Festus": 8,
    "Abay Tsehaye": 4,
    "Abdelaziz Bouteflika": 0,
    "Abdelaziz Djerad": 0,
    "Abdelmadjid Tebboune": 0,
    "Abebaw Butako": 4,
    "Abedi Pele": 5,
    "Abel Edime": 8,
    "Abosede Olajide": 8,
    "Abubeker Nassir": 4,
    "Abuya Solomon": 8,
    "Adam Bombolb": 2,
    "Adam Ounas": 0,
    "Adane Girma": 4,
    "Adebimpe Olarewaju": 8,
    "Adedini Adeola": 8,
    "Adegoke Akinyele": 8,
    "Adegoke Olamide": 8,
    "Adem Zorgane": 0,
    "Adesua Etomi": 8,
    "Adigun Pelumi": 8,
    "Agostinho Kapaia": 1,
    "Ahmed Ben Bella": 0,
    "Ahmed Elmohamady": 3,
    "Ahmed Hegazi": 3,
    "Ahmed Kathrada": 9,
    "Ahmed Magdy": 3,
    "Ahmed Mahgoub": 3,
    "Ahmed Mazouz": 0,
    "Ahmed Saad": 3,
    "Ahmed Sayed": 3,
    "Ajewole Fasanmi Richard": 8,
    "Ajewole Olaitan": 8,
    "Akua Dansua": 5,
    "Akwa": 1,
    "Aladeokin A. Abiodun": 8,
    "Albert Luthuli": 9,
    "Alemu Aga": 4,
    "Alula Girma": 4,
    "Amin Askar": 4,
    "AminB": 4,
    "Amira Selim": 3,
    "Amos Wako": 6,
    "Amr Waked": 3,
    "Andre Ayew": 5,
    "Andre Gaspar Mendes de Carvalho": 1,
    "Anifowose Mariam": 8,
    "Anoushka": 3,
    "Anssa Mandi": 0,
    "Antanio Mendona": 1,
    "Antjie Krog": 9,
    "Anton Rupert": 9,
    "Anuoluwapo Comfort Kolawole": 8,
    "Aristote Nsiala": 2,
    "Arlindo Barbeitos": 1,
    "Arthur Masuaku": 2,
    "Ary Papel": 1,
    "Asamoah Gyan": 5,
    "Aster Aweke": 4,
    "Avril": 6,
    "Babatunde Oladogba": 8,
    "Basetsana Kumalo": 9,
    "Becca": 5,
    "Behailu Assefa": 4,
    "Behati Prinsloo": 7,
    "Bela": 1,
    "Ben Malango": 2,
    "Ben Ulenga": 7,
    "Ben Youcef": 0,
    "Benjamin Hauwanga": 7,
    "Benjamin Ochieng": 6,
    "Benson Shilongo": 7,
    "Berhane Gebrekiristos": 4,
    "Bertrand Bisimwa": 2,
    "Bethlehem Tilahun Alemu": 4,
    "Beverly Naya": 8,
    "Beyers Naude": 9,
    "Bience Gawanas": 7,
    "Bill Asamoah": 5,
    "Bill Sellanga": 6,
    "Birtukan Mideksa": 4,
    "Bishop David Abioye": 8,
    "Bishop David Oyedepo": 8,
    "Black Sherif": 5,
    "Bodunha": 8,
    "Bonginkosi Dlamini": 9,
    "Bozi Boziana": 2,
    "Branca Manuel Espirito Santo": 1,
    "Brenda Fassie": 9,
    "Brenda Wairimu": 6,
    "Britier": 6,
    "Buhari": 8,
    "C. Manuel Cafumana": 1,
    "Carlos Conceicao": 1,
    "Carmen Suleiman": 3,
    "Carolina Cerqueira": 1,
    "Catherine Kamau": 6,
    "Cedric Bakambu": 2,
    "Celso Roberto": 1,
    "Chadli Bendjedid": 0,
    "Chahrazad Kracheni": 0,
    "Chancel Mbemba Mangulu": 2,
    "Chara": 5,
    "Charlize Theron": 9,
    "Cheb Hamidou": 0,
    "Cheb Rami": 0,
    "Cheb Reda Diamond": 0,
    "Chinua Achebe": 8,
    "Chris Attoh": 5,
    "Chris Hani": 9,
    "Chris Kirubi": 6,
    "Christabel Ekeh": 5,
    "Christian Atsu": 5,
    "Christian Luyindama": 2,
    "Christian Malanga": 2,
    "Christianah Oyewale": 8,
    "Christine Wawira": 6,
    "Claude Wilfrid Etoka": 2,
    "Clemens Kapuuo": 7,
    "Collin Benjamin": 7,
    "Coussoud-Mavoungou": 2,
    "Cyril Ramaphosa": 9,
    "Dadju": 2,
    "Damilola": 8,
    "Damilola Orimolade": 8,
    "Daniel Amartey": 5,
    "Daniel arap Moi": 6,
    "Daniel Aselo Okito": 2,
    "Daniel Francois Malan": 9,
    "Daniel McKorley": 5,
    "Danny Jordaan": 9,
    "David Ndjavera": 7,
    "Degu Debebe": 4,
    "Demeke Mekonnen": 4,
    "Denzil Haoseb": 7,
    "Deon Kavendji": 7,
    "Desmond Tutu": 9,
    "Didi Stone Olomide": 2,
    "Dieudonne Ndinga Moukala": 2,
    "Djalma Campos": 1,
    "Don Jazzy": 8,
    "Dullah Omar": 9,
    "Eddie Kadi": 2,
    "Eddie Nartey": 5,
    "Edi Gathegi": 6,
    "Egas Cacintura": 1,
    "Elijah Lagat": 6,
    "Elijah Ngurare": 7,
    "Elizabeth Ohene": 5,
    "Elizabeth Teissier": 0,
    "Ephrem Amare": 4,
    "Eric Wainaina": 6,
    "Erica Chissapa": 1,
    "Ermias Amelga": 4,
    "Eshele Botende": 2,
    "Eslin Kamuhanga": 7,
    "Essam El-Hadary": 3,
    "Eugkne Terre Blanche": 9,
    "Evoloko Jocker": 2,
    "Ewatomi": 8,
    "Ezenwo Nyesom Wike": 8,
    "F. W. de Klerk": 9,
    "Fatima Meer": 9,
    "Felix Afena-Gyan": 5,
    "Femi": 8,
    "Fethi Manar": 0,
    "Fikru Teferra": 4,
    "Flavo Amado": 1,
    "Frank Acheampong": 5,
    "Frank Artus": 5,
    "Frankie Fredericks": 7,
    "Fredy": 1,
    "Fuad Ibrahim": 4,
    "Gael Kakuta": 2,
    "Gary Player": 9,
    "Gatoch Panom": 4,
    "Gedeon Kalulu": 2,
    "Gelila Bekele": 4,
    "Gelson Dala": 1,
    "Getaneh Kebede": 4,
    "Gideon Mensah": 5,
    "Girley Jazama": 7,
    "Godwin Obaseki": 8,
    "Grace Ogot": 6,
    "Guilherme Afonso": 1,
    "Hage Geingob": 7,
    "Haile Gebrselassie": 4,
    "Hamdi Fathi": 3,
    "Hanan Tarq": 4,
    "Hany Ramzy": 3,
    "Happiness": 8,
    "Haris Belkebla": 0,
    "Harry Simon": 7,
    "Hassan Kachach": 0,
    "Heino Senekal": 7,
    "Helalia Johannes": 7,
    "Helder Costa": 1,
    "Helen Suzman": 9,
    "Hendrik Somaeb": 7,
    "Hendrik Verwoerd": 9,
    "Hicham Boudaoui": 0,
    "Hossam Habib": 3,
    "Hossam Hassan": 3,
    "Houari Boumediene": 0,
    "Hussein El Shahat": 3,
    "Imaye Taga": 4,
    "Isaac Maria dos Anjos": 1,
    "Isabel dos Santos": 1,
    "Ismael Bennacer": 0,
    "J. R. R. Tolkien": 9,
    "Jackie Appiah": 5,
    "Jackson Muleka": 2,
    "James Mwangi": 6,
    "Jan du Toit": 9,
    "Jawar Mohammed": 4,
    "Jean Andeka": 2,
    "Jean-Claude Bastos de Morais": 1,
    "Jean-Pierre Bemba": 2,
    "Jemal Tassew": 4,
    "Jessica Beshir": 4,
    "Jessy Matador": 2,
    "Joao Baptista Borges": 1,
    "Joao Lourenco": 1,
    "Joaquim David": 1,
    "Joe Slovo": 9,
    "Joel Haikali": 7,
    "Johann Rupert": 9,
    "John Atta Mills": 5,
    "John Dumelo": 5,
    "Johnny Clegg": 9,
    "Jomo Kenyatta": 6,
    "Jonas Ramalho": 1,
    "Jonathan Buatu": 1,
    "Jonl Kimwaki": 2,
    "Jonty Rhodes": 9,
    "Jordan Ayew": 5,
    "Jordan Botaka": 2,
    "Jose Eduardo dos Santos": 1,
    "Joseph Siaw Agyapong": 5,
    "Josiah Mwangi Kariuki": 6,
    "Josky Kiambukuta": 2,
    "Juanita du Plessis": 7,
    "Kader Japonais": 0,
    "Kahush": 6,
    "Kaizer Motaung": 9,
    "Kaka Sungura": 6,
    "Kali": 2,
    "Kamel Belghazi": 0,
    "Kamo Mphela": 9,
    "Kayode": 8,
    "Kehinde": 8,
    "Kemi": 8,
    "Kevin-Prince Boateng": 5,
    "Khaligraph Jones": 6,
    "Koigi wa Wamwere": 6,
    "Kuami Eugene": 5,
    "Kunleola Adebayo": 8,
    "Kwadwo Asamoah": 5,
    "Kwaku Manu": 5,
    "Kwesi Arthur": 5,
    "Lakhdar Brahimi": 0,
    "Larbi Ben Mhid": 0,
    "Lazarus Kaimbi": 7,
    "Leon Schuster": 9,
    "Liamine Zeroual": 0,
    "Liya Kebede": 4,
    "Loco": 1,
    "Lord Paul Boateng": 5,
    "Lucien Ebata": 2,
    "Lydia Forson": 5,
    "Lyes Salem": 0,
    "Lyna Khoudri": 0,
    "Madilu System": 2,
    "Mahder Assefa": 4,
    "Mahmoud Hamdy": 3,
    "Majid Michel": 5,
    "Mama Ngina Kenyatta": 6,
    "Mandoza": 9,
    "Mangosuthu Buthelezi": 9,
    "Manucho": 1,
    "Marco Airosa": 1,
    "Marcus Samuelsson": 4,
    "Marie Daulne": 2,
    "Mark Shuttleworth": 9,
    "Marlice van Vuuren": 7,
    "Martha Ankomah": 5,
    "Mary Oyaya": 6,
    "Mateus Galiano da Costa": 1,
    "Mayowa Afolabi": 8,
    "MBala Nzola": 2,
    "Mejja": 6,
    "Mekonnen Knife": 4,
    "Mercy Myra": 6,
    "Merouane Guerouabi": 0,
    "Merveille Bokadi": 2,
    "Micaela Reis": 1,
    "Michael Crichton": 9,
    "Michael Essien": 5,
    "Michael Kennedy Naiboi": 6,
    "Michael Olunga": 6,
    "Michelle McLean": 7,
    "Mido": 3,
    "Mike Ezuruonye": 8,
    "Mike Sonko": 6,
    "Milson": 1,
    "Minyahil Teshome": 4,
    "Miriam Makeba": 9,
    "Mohamed Abdelmonem": 3,
    "Mohamed Aboutrika": 3,
    "Mohamed Elneny": 3,
    "Mohamed Fares": 0,
    "Mohamed Fayed": 3,
    "Mohamed Hussein Tantawi": 3,
    "Mohamed Laid Benamor": 0,
    "Mohamed Magdy": 3,
    "Mohamed Mansour": 3,
    "Mohamed Salah": 3,
    "Mohamed Sherif": 3,
    "Mohamed Zidan": 3,
    "Mohammed Al Amoudi": 4,
    "Mohammed El Shenawy": 3,
    "Mohammed Kudus": 5,
    "Mohammed Ouseb": 7,
    "Mohammed Salisu": 5,
    "Moise Katumbi": 2,
    "Mose Se Sengo": 2,
    "Moses Wetangula": 6,
    "Moshe Abebe": 4,
    "Mostafa Fathi": 3,
    "Mostafa Mohamed": 3,
    "Mouni Bouallam": 0,
    "Mourad Eulmi": 0,
    "Muhammad Boudiaf": 0,
    "Muluken Melesse": 4,
    "Mustapha Laribi": 0,
    "Mwai Kibaki": 6,
    "Nader Ghabbour": 3,
    "Nader Hamdy": 3,
    "Nadia Buari": 5,
    "Nadia Mukami": 6,
    "Naguib Sawiris": 3,
    "Nancy Isime": 8,
    "Nancy Johannes": 7,
    "Nassef Sawiris": 3,
    "Nelson da Luz": 1,
    "Nelson Mandela": 9,
    "Neway Debebe": 4,
    "Nhatty Man": 4,
    "Nianell": 7,
    "Nicholas Biwott": 6,
    "Nick Mutumqa": 6,
    "Nicole Garcia": 0,
    "Nikita Kering": 6,
    "Nixau Toma": 7,
    "Nkosazana Dlamini-Zuma": 9,
    "Nour El Sayed": 3,
    "Nyashinski": 6,
    "Obasanjo": 8,
    "Okon Abosede Ola": 8,
    "Okyeame Kwame": 5,
    "Olagbende Ebenezer": 8,
    "Olaku Temitope": 8,
    "Oliver Litondo": 6,
    "Oliver Risser": 7,
    "Oliver Tambo": 9,
    "Oluwaseyi Makinde": 8,
    "Oluwatoyin Olajumoke": 8,
    "Omar Marmoush": 3,
    "Omenuke Mfulu": 2,
    "Omer Ali Shifaw": 4,
    "Onsi Sawiris": 3,
    "Oscar Maritu": 2,
    "Otile Brown": 6,
    "Oumed Oukri": 4,
    "Owolabi Rukayat Adeshola": 8,
    "Oyinkansola": 8,
    "P. W. Botha": 9,
    "Papa Wemba": 2,
    "Pascal Tokodi": 6,
    "Pastor Enoch Adeboye": 8,
    "Patrice Motse": 9,
    "Patricia de Lille": 9,
    "Patsha Bay": 2,
    "Paul Kruger": 9,
    "Paulao": 1,
    "Paulino Baptista": 1,
    "Paulus Ambunda": 7,
    "Percy Montgomery": 9,
    "Peter Shalulile": 7,
    "Pieter Dirk Uys": 9,
    "Prince David Osei": 5,
    "Quinzinho": 1,
    "Raila Odinga": 6,
    "Ramy Bensebaini": 0,
    "Ramy Gamal": 3,
    "Ramy Sabry": 3,
    "Raouf Ghabbour": 3,
    "Raphael Soriano Katoto Katebe": 2,
    "Ras Samuel Weldaabzgi": 4,
    "Rasselas Lakew": 4,
    "Ray Lema": 1,
    "Raymond Ofula": 6,
    "Razundara": 5,
    "Reggie Rockstone": 5,
    "Richard Leakey": 6,
    "Riyad Mahrez": 0,
    "Robert Nauseb": 7,
    "Robert Sobukwe": 9,
    "Romand": 3,
    "Ronald Ketjijere": 7,
    "Rudolf Bester": 7,
    "Ruth Ndulu Maingi": 6,
    "Ruth Negga": 3,
    "Ryan Nyambe": 7,
    "Saed Benrahma": 0,
    "Sahle Work Zewde": 4,
    "Saladin Said": 4,
    "Salah Aougrout": 0,
    "Salma Mumin": 5,
    "Sam Mangwana": 2,
    "Sam Morsy": 8,
    "Sami Dan": 9,
    "Samih Sawiris": 3,
    "Samir Guemriche": 0,
    "Samuel Bastien": 2,
    "Samuel Kuffour": 5,
    "Sanaipei Tande": 6,
    "Sarah Maldoror": 2,
    "Sarkodie": 5,
    "Sauti Sol": 6,
    "Sebhat Nega": 4,
    "Senait Ashenafi": 4,
    "Senait Ghebrehiwet Mehari": 4,
    "Seyoum Mesfin": 4,
    "Shafik Gabr": 3,
    "Shatta Wale": 5,
    "Shewit Mezgebo": 4,
    "Shiloh Jolie-Pitt": 9,
    "Shirine Boutella": 0,
    "Sindika Dokolo": 2,
    "Slyva Mirabel": 1,
    "Smith Asante": 5,
    "Sofia Boutella": 0,
    "Steve Biko": 9,
    "Steve Hofmeyr": 9,
    "Sulley Muntari": 5,
    "Suzanna Owoyo": 6,
    "Tabu Ley Rochereau": 2,
    "Tagne": 1,
    "Tangeni Shipahu": 7,
    "Tarek Hamed": 3,
    "Tashitaa Tufaa": 4,
    "Thabo Mbeki": 9,
    "Theodros Teshome": 4,
    "Thomas Partey": 5,
    "Tiiwtiiw": 1,
    "Tinubu": 8,
    "Tippi": 9,
    "Toke Makinwa": 8,
    "Tokyo Sexwale": 9,
    "Tolulope Akinyombo": 8,
    "Tony Gatlif": 9,
    "Tony Leon": 9,
    "Tony Yeboah": 5,
    "Trevor Manuel": 9,
    "Trezeguet": 3,
    "Uhuru Kenyatta": 6,
    "Victor Wanyama": 6,
    "Virgil Vries": 7,
    "Vivalda Dula": 2,
    "Wahu": 6,
    "Walter Sisulu": 9,
    "Wangari Maathai": 6,
    "Wendo Musaly": 6,
    "Wendy Shay": 5,
    "Willem Mwedihanga": 7,
    "William Samoei Ruto": 6,
    "Willy Stephanus": 7,
    "Wiyaala": 7,
    "Wole Soyinka": 8,
    "Yamba Asha": 2,
    "Yannick Bolasie": 2,
    "Yasmin Said": 4,
    "Yasmine Niazy": 3,
    "Yasseen Mansour": 3,
    "Yasser Ibrahim": 3,
    "Yola Semedo": 1,
    "Youcef Atal": 0,
    "Youlou Mabiala": 2,
    "Youssef Mansour": 3,
    "Yvonne Chaka Chaka": 9,
    "Yvonne Nelson": 8,
    "Zahara Marley Jolie-Pitt": 9,
    "Zahia Dehar": 0,
    "Zainab Balogun": 8,
    "Zandre Campos": 7,
    "Zeritu Kebede": 4,
    "Zito Luvumbo": 1,
    "Zizi Adel": 0,
    "Zola Matumona": 2
}
